apiVersion: v1
data:
  ENV: "kubernetes"
  DB_DATABASE: sample_app
  # サービス名、ネームスペース、リソース、同じクラスター内という記述
  DB_HOST: mysql.database.svc.cluster.local
  DB_USER: root
kind: ConfigMap
metadata:
  # creationTimestamp: null
  name: sample-app
